# SOLVER
TIME_RES: 0.2  # s
ALPHA_SCALING_NUM: 5
VERBOSE: False
TIME_HORIZON: 3.0  # s (2.0, 12.0)
MAX_ITER: 35 # (30, 100)

# RHC
N_SIM: 120

# OPINION DYNAMICS
LOOK_AHEAD: 5

# ENVIRONMENT
TOLL_STATION_PX_LB: 50
TOLL_STATION_PX_UB: 80
TOLL_STATION_2_PY: 3.5
TOLL_STATION_WIDTH: 3.5

# NON-CONSTRAINT COST
GOAL_PY_1: 7.0
GOAL_PY_2: 0.0
GOAL_W_P1_1: 5.0
GOAL_W_P1_2: 15.0
GOAL_W_P2_1: 15.0
GOAL_W_P2_2: 5.0
GOAL_VEL: 3.0
GOAL_PX_LB: 25

# CONSTRAINT COST
ROAD_BOUNDARY_UPPER_THRESHOLD: 8.5
ROAD_BOUNDARY_LOWER_THRESHOLD: -1.5
PROXIMITY_THRESHOLD: 6.5
CTRL_LIMIT_SLACK_MULTIPLIER: 1.0

# STATE CONSTRAINTS
MAXV: 4.0  # m/s
MINV: 2.0

# INPUT CONSTRAINTS
A_MIN: -2.0
A_MAX: 1.0
W_MIN: -0.1
W_MAX: 0.1

# MISC
SAVE_TRAJ: True